apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - name: istio-proxy
          image: "quay.io/ibm/istio-proxyv2-ppc64le:1.16.0"
