apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-configuration-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
